### ISSUE TITLE
Adafruit PiCowbell Camera Breakout (for Pico W)

### ISSUE THREAD

**Issue by sgbaird** [AccelerationConsortium/ac-training-lab#118]
@Jonathan-Woo, thoughts? https://www.adafruit.com/product/5946

**Comment by Jonathan-Woo** [comment]
Sorry what's the motivation for this camera?

**Comment by sgbaird** [comment]
Something microcontroller based rather than requiring a single board computer, reducing cost and maybe simplifying the form factor and setup. However, the Pi Zero 2W may be close enough in price to the Pico W that it's not really a big consideration.

A while back, I had looked into microcontroller based cameras for the Pico W, but there weren't a lot of robust options.

I'll keep this one on the backlog.
