### ISSUE TITLE
API info for workflow colab notebooks

### ISSUE THREAD

**Issue by sgbaird** [AccelerationConsortium/ac-training-lab#121]
In the colab notebooks for workflows (e.g., MyCobot 280 Pi, Pioreactor), let's include a cell that uses `view_api()` from https://www.gradio.app/guides/getting-started-with-the-python-client#inspecting-the-api-endpoints.

Related: #77

**Comment by gursi26** [comment]
completed on the cobot demo notebook

**Comment by linx5o** [comment]
Done
