### ISSUE TITLE
"Use custom broker" checkbox and form within hf streamlit apps

### ISSUE THREAD

**Issue by sgbaird** [AccelerationConsortium/ac-training-lab#73]
Ideally, I'd like for people to be able to swap out the broker with their own. For non-public AC brokers (currently applies to the microscope, but will also apply to the cobot), we'll want to make sure the broker information isn't exposed.

<img src=https://github.com/user-attachments/assets/94368f2c-6416-4533-8516-8a4f19f45b31 width=250>

Thoughts on a checkbox or dropdown, that if a user clicks it opens the following form?

<img src=https://github.com/user-attachments/assets/4ba77e4e-5d91-4ca0-b40b-a3cbe70aca3f width=250>

@gursi26 @linx5o 

EDIT: here's the [app.py](https://huggingface.co/spaces/AccelerationConsortium/light-mixing/blob/main/app.py) for the light-mixing demo

**Comment by gursi26** [comment]
@sgbaird Is this a custom broker or custom credentials for HiveMQ? do all brokers follow the same credential format (username, password, host url, port)?

**Comment by sgbaird** [comment]
> @sgbaird Is this a custom broker or custom credentials for HiveMQ? do all brokers follow the same credential format (username, password, host url, port)?

I meant custom HiveMQ broker + credentials (i.e., new instance on HiveMQ), but it's also a good point - generally if you have those four things you can swap out the broker completely - e.g., move to a mosquitto broker, as long as certificates and security are set up in a compatible way

**Comment by gursi26** [comment]
alright, implemented this in my recent push https://huggingface.co/spaces/AccelerationConsortium/cobot280pi/commit/90958100bcd0281f68f55dfe275bd84b448c4103

**Comment by linx5o** [comment]
ok, i will implement

**Comment by sgbaird** [comment]
@linx5o see https://huggingface.co/spaces/AccelerationConsortium/cobot280pi/blob/6341f4f3454dd00b0352a02e666b8935bd8c580c/app.py#L52 for an example of loading the default credentials from an env var.

**Comment by sgbaird** [comment]
> > @linx5o see https://huggingface.co/spaces/AccelerationConsortium/cobot280pi/blob/6341f4f3454dd00b0352a02e666b8935bd8c580c/app.py#L52 for an example of loading the default credentials from an env var.
> 
> The default creds are implemented using env vars in Hugging face. However having it in the form is easier for running it locally.

Oh, got it. Often, I'll use env vars in a VS Code debug launch configuration, but I'm not sure what a convenient way would be with streamlit since it's run from the command line.

EDIT: looks like a terminal profile would do the trick: https://code.visualstudio.com/docs/terminal/profiles.

Forgive the perhaps overly cautious sentiment 😅

**Comment by sgbaird** [comment]
@linx5o @gursi26 feel free to reopen if needed.
